use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/NoNameOrganazation/LNSpec.git'

platform :ios, '9.0'

target 'LNModuleProtocol_Example' do
  pod 'LNModuleProtocol', :path => '../'

  target 'LNModuleProtocol_Tests' do
    inherit! :search_paths

    
  end
end
